<div class="about">
	<p>No one likes go openings.</p>

	<p>They're hard to remember, and they're hard to practice.</p>

	<p>This website is an attempt to make them easier to learn.</p>

	<p>Every day, a new opening is generated.</p>

	<p>You can practice it, or you can play around with it.</p>

	<p>The goal is to make it easier to learn openings.</p>

	<p>
		If you have any feedback or a favorite opening, please let me know!
		<a href="mailto:oh.snap@mom.dog">oh.snap@mom.dog</a>
	</p>

	<p>
		The above (minus the first line) was generated by GitHub CoPilot. You don't actually need to
		know go openings to git good. My super strong friend told me so, and so did ZChenMike (ever
		heard of him?). Learn all the openings you want, I'm going to do go problems like they told me
		to. They're more fun anyways! Anyone trying to tell you otherwise is trying to trick you into
		wasting time so they can get ahead. Don't fall for it!
	</p>

	<p>
		But if you do decide to use the site, do so at your own risk. I'm just grabbing random openings from the interwebs so...
		who knows if they're even right. Pre-AI, post-AI, beats me 🤷‍♀️
	</p>

	<p>
		And the second this costs money I'm taking it down. I'm broke.
	</p>
</div>
